/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpv_galileo;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author gonfe
 */
public class Login extends javax.swing.JFrame {

    /*BD data*/
    private static String url = "remotemysql.com:3306";
    private static String bd = "uCCuEdldr1";
    private static String bd_user = "uCCuEdldr1";
    private static String bd_pass = "69EcIGw5Nd";
    public static Connection conexion = Conexion.mySQL(url, bd, bd_user, bd_pass);

    public static String User = null;
    public static String Id = null;

    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        Text_Username = new javax.swing.JLabel();
        Txt_Username = new javax.swing.JTextField();
        Text_Pasword = new javax.swing.JLabel();
        Txt_Password = new javax.swing.JPasswordField();
        Btn_Login = new javax.swing.JButton();
        Btn_conf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Text_Username.setText("Usuario");

        Text_Pasword.setText("Contraseña");

        Txt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_PasswordKeyPressed(evt);
            }
        });

        Btn_Login.setText("Login");
        Btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LoginActionPerformed(evt);
            }
        });

        Btn_conf.setText("Configuración");
        Btn_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_confActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Pasword)
                    .addComponent(Text_Username))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(Txt_Username))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_conf)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Btn_Login)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Username)
                    .addComponent(Txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Pasword)
                    .addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_conf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LoginActionPerformed
        Iniciar();
    }//GEN-LAST:event_Btn_LoginActionPerformed

    private void Txt_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_PasswordKeyPressed
        if (evt.getKeyCode() == 10) {
            Iniciar();
        }
    }//GEN-LAST:event_Txt_PasswordKeyPressed

    private void Btn_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_confActionPerformed
        JTextField url = new JTextField(20);
        JTextField bd = new JTextField(20);
        JTextField bd_user = new JTextField(20);
        JTextField bd_pass = new JTextField(20);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("url:"));
        myPanel.add(url);
        myPanel.add(Box.createHorizontalStrut(15));
        myPanel.add(new JLabel("Base de datos:"));
        myPanel.add(bd);
        myPanel.add(Box.createVerticalStrut(15));
        myPanel.add(new JLabel("Usuario:"));
        myPanel.add(bd_user);
        myPanel.add(Box.createVerticalStrut(15));
        myPanel.add(new JLabel("Contraseña:"));
        myPanel.add(bd_pass);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Configuración conexión base de datos", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println("-------- MySQL JDBC Test de conexión ------------");

            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "<html><body>Se a producido un error con el driver de la base de datos <br>Error: " + e, "Error driver", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                return;
            }
            Connection connection = null;
            try {
                connection = (Connection) DriverManager.getConnection("jdbc:mysql://" + url.getText() + "/" + bd.getText() + "", bd_user.getText(), bd_pass.getText());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "<html><body>Se a producido un error en la conexion<br>Error: " + e, "Error conexión", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                return;
            }
            if (connection != null) {
                System.out.println("Conexion aceptada");
                Login.url = url.getText();
                Login.bd = bd.getText();
                Login.bd_user = bd_user.getText();
                Login.bd_pass = bd_pass.getText();
                conexion = Conexion.mySQL(Login.url, Login.bd, Login.bd_user, Login.bd_pass);
            } else {
                JOptionPane.showMessageDialog(null, "Se a producido un error en la conexion", "Error conexión", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Btn_confActionPerformed

    private void Iniciar() {
        ArrayList<String[]> users = Conexion.leerTabla(conexion, "select * from USUARIOS");
        for (int i = 1; i < users.size(); i++) {
            String[] user = users.get(i);
            if (user[1].equals(Txt_Username.getText())) {
                if (user[2].equals(Txt_Password.getText())) {
                    System.out.println("Inicio de sesión correcto");
                    User = user[1];
                    Id = user[0];
                    Terminal main = new Terminal();
                    main.setVisible(true);
                    this.setVisible(false);
                    break;
                } else {
                    if (i + 1 == users.size()) {
                        JOptionPane.showMessageDialog(null, "La contraseña es incorrecta", "Error contraseña", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                if (i + 1 == users.size()) {
                    JOptionPane.showMessageDialog(null, "El usuario es incorrecto o no a sido encontrado", "Error usuario", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Login;
    private javax.swing.JButton Btn_conf;
    private javax.swing.JLabel Text_Pasword;
    private javax.swing.JLabel Text_Username;
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JTextField Txt_Username;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
